BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path=public,extensions;
CREATE TEMP TABLE lan_results(line text);
GRANT INSERT ON lan_results TO authenticated,anon,kiosk_display;
INSERT INTO lan_results SELECT no_plan();
INSERT INTO roles(code,name) VALUES('LAN_ACL_TEST','LAN test');
INSERT INTO permissions(code,module,action) VALUES('lan.devices.manage','lan','manage') ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_code,permission_code) VALUES('LAN_ACL_TEST','lan.devices.manage');
CREATE TEMP TABLE lan_fixture AS SELECT gen_random_uuid() AS actor,gen_random_uuid() AS device,gen_random_uuid() AS other;
INSERT INTO auth.users(id) SELECT actor FROM lan_fixture;
INSERT INTO user_profiles(id,auth_user_id,employee_code,full_name,pin_hash,role_code)
SELECT actor,actor,'LAN-'||actor::text,'LAN test','not-a-login','LAN_ACL_TEST' FROM lan_fixture;
INSERT INTO lan_devices(id,code,name,device_type) SELECT device,'LAN-TEST-'||device::text,'Test tablet','tablet' FROM lan_fixture
UNION ALL SELECT other,'LAN-TEST-'||other::text,'Other tablet','tablet' FROM lan_fixture;
CREATE TEMP TABLE lan_code AS SELECT manage_lan_device_v1(actor,'issue',device) AS result FROM lan_fixture;
INSERT INTO lan_results SELECT throws_ok($t$SELECT manage_lan_device_v1(NULL,'list')$t$,'42501','permission_denied','management requires active actor and permission');
INSERT INTO lan_results SELECT throws_ok($t$SELECT authenticate_lan_device_v1(repeat('a',64),repeat('b',64))$t$,'42501','device_unauthorized','wrong code refused');
CREATE TEMP TABLE paired AS SELECT authenticate_lan_device_v1(repeat('a',64),encode(extensions.digest((SELECT result->>'pairing_code' FROM lan_code),'sha256'),'hex')) AS result;
INSERT INTO lan_results SELECT is((SELECT result->>'id' FROM paired),(SELECT device::text FROM lan_fixture),'pair resolves the registered device');
INSERT INTO lan_results SELECT ok(NOT ((SELECT result->'permissions' FROM paired) ? 'drawer.open'),'tablet has no drawer permission');
INSERT INTO lan_results SELECT throws_ok($t$SELECT authenticate_lan_device_v1(repeat('c',64),encode(extensions.digest((SELECT result->>'pairing_code' FROM lan_code),'sha256'),'hex'))$t$,'42501','device_unauthorized','used code cannot pair a different secret');
INSERT INTO lan_results SELECT lives_ok($t$SELECT authenticate_lan_device_v1(repeat('a',64),encode(extensions.digest((SELECT result->>'pairing_code' FROM lan_code),'sha256'),'hex'))$t$,'same secret retry accepted');
INSERT INTO lan_results SELECT throws_ok($t$SELECT authenticate_lan_device_v1(repeat('a',64),NULL,(SELECT other FROM lan_fixture))$t$,'42501','device_unauthorized','secret cannot claim another device');
INSERT INTO lan_results SELECT is((SELECT count(*)::integer FROM update_lan_heartbeat_v3(ARRAY[(SELECT result->>'code' FROM paired)])),1,'server heartbeat accepts paired device');
UPDATE lan_devices SET is_active=false WHERE id=(SELECT device FROM lan_fixture);
INSERT INTO lan_results SELECT is((SELECT count(*)::integer FROM update_lan_heartbeat_v3(ARRAY[(SELECT result->>'code' FROM paired)])),0,'inactive device ignored');
INSERT INTO lan_results SELECT is((SELECT is_active FROM lan_devices WHERE id=(SELECT device FROM lan_fixture)),false,'heartbeat never reactivates device');
INSERT INTO lan_results SELECT is((SELECT count(*)::integer FROM jsonb_array_elements(get_lan_registry_v1()->'devices') d WHERE d->>'id'=(SELECT device::text FROM lan_fixture)),0,'inactive device omitted from registry');
UPDATE lan_devices SET is_active=true WHERE id=(SELECT device FROM lan_fixture);
INSERT INTO lan_results SELECT is((SELECT count(*)::integer FROM jsonb_array_elements(get_lan_registry_v1()->'devices') d WHERE d->>'id'=(SELECT device::text FROM lan_fixture)),1,'active paired device in registry');
SELECT manage_lan_device_v1(actor,'revoke',device) FROM lan_fixture;
INSERT INTO lan_results SELECT throws_ok($t$SELECT authenticate_lan_device_v1(repeat('a',64),NULL,(SELECT device FROM lan_fixture))$t$,'42501','device_unauthorized','revocation refuses device');
INSERT INTO lan_results SELECT is((SELECT count(*)::integer FROM jsonb_array_elements(get_lan_registry_v1()->'devices') d WHERE d->>'id'=(SELECT device::text FROM lan_fixture)),0,'revoked device removed from registry');
CREATE TEMP TABLE expired AS SELECT manage_lan_device_v1(actor,'issue',other) AS result FROM lan_fixture;
UPDATE lan_device_credentials SET pairing_expires_at=now()-interval '1 second' WHERE device_id=(SELECT other FROM lan_fixture);
INSERT INTO lan_results SELECT throws_ok($t$SELECT authenticate_lan_device_v1(repeat('d',64),encode(extensions.digest((SELECT result->>'pairing_code' FROM expired),'sha256'),'hex'))$t$,'42501','device_unauthorized','expired code refused');
INSERT INTO lan_results SELECT ok(NOT has_table_privilege('anon','public.lan_device_credentials','SELECT'),'anon: no credential access');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('anon','public.manage_lan_device_v1(uuid,text,uuid,text[])','EXECUTE'),'anon: manage_lan_device_v1(uuid,text,uuid,text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('anon','public.authenticate_lan_device_v1(text,text,uuid)','EXECUTE'),'anon: authenticate_lan_device_v1(text,text,uuid) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('anon','public.get_lan_registry_v1()','EXECUTE'),'anon: get_lan_registry_v1() denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('anon','public.update_lan_heartbeat_v3(text[])','EXECUTE'),'anon: update_lan_heartbeat_v3(text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('anon','public.send_items_to_kitchen(uuid[])','EXECUTE'),'anon: send_items_to_kitchen(uuid[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_table_privilege('authenticated','public.lan_device_credentials','SELECT'),'authenticated: no credential access');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('authenticated','public.manage_lan_device_v1(uuid,text,uuid,text[])','EXECUTE'),'authenticated: manage_lan_device_v1(uuid,text,uuid,text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('authenticated','public.authenticate_lan_device_v1(text,text,uuid)','EXECUTE'),'authenticated: authenticate_lan_device_v1(text,text,uuid) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('authenticated','public.get_lan_registry_v1()','EXECUTE'),'authenticated: get_lan_registry_v1() denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('authenticated','public.update_lan_heartbeat_v3(text[])','EXECUTE'),'authenticated: update_lan_heartbeat_v3(text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('authenticated','public.send_items_to_kitchen(uuid[])','EXECUTE'),'authenticated: send_items_to_kitchen(uuid[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_table_privilege('kiosk_display','public.lan_device_credentials','SELECT'),'kiosk_display: no credential access');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('kiosk_display','public.manage_lan_device_v1(uuid,text,uuid,text[])','EXECUTE'),'kiosk_display: manage_lan_device_v1(uuid,text,uuid,text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('kiosk_display','public.authenticate_lan_device_v1(text,text,uuid)','EXECUTE'),'kiosk_display: authenticate_lan_device_v1(text,text,uuid) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('kiosk_display','public.get_lan_registry_v1()','EXECUTE'),'kiosk_display: get_lan_registry_v1() denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('kiosk_display','public.update_lan_heartbeat_v3(text[])','EXECUTE'),'kiosk_display: update_lan_heartbeat_v3(text[]) denied');
INSERT INTO lan_results SELECT ok(NOT has_function_privilege('kiosk_display','public.send_items_to_kitchen(uuid[])','EXECUTE'),'kiosk_display: send_items_to_kitchen(uuid[]) denied');
SET LOCAL ROLE authenticated;
INSERT INTO lan_results SELECT throws_ok($t$SELECT send_items_to_kitchen(ARRAY[gen_random_uuid()])$t$,'42501','permission denied for function send_items_to_kitchen','legacy kitchen call refused');
INSERT INTO lan_results SELECT throws_ok($t$SELECT update_lan_heartbeat_v3(ARRAY['not-an-identity'])$t$,'42501','permission denied for function update_lan_heartbeat_v3','direct heartbeat refused');
RESET ROLE;
INSERT INTO lan_results SELECT * FROM finish();
SELECT line FROM lan_results;
ROLLBACK;
