// packages/domain/src/inventory/classifyMovement.ts
// Session 12 — classify a movement for UI affordances / audit display.

import type { StockMovement } from './types.js';

export interface MovementClassification {
  /** 'IN' if quantity > 0, otherwise 'OUT' (qty === 0 also flags as OUT but is filtered upstream). */
  direction: 'IN' | 'OUT';
  /** Sale or sale void — generated by checkout flows. */
  isSale: boolean;
  /** Operator-initiated change (purchase, adjustment, waste, production). */
  isAdmin: boolean;
}

export function classifyMovement(mvt: StockMovement): MovementClassification {
  const direction: 'IN' | 'OUT' = mvt.quantity > 0 ? 'IN' : 'OUT';
  const isSale = mvt.movementType === 'sale' || mvt.movementType === 'sale_void';
  const isAdmin =
    mvt.movementType === 'adjustment' ||
    mvt.movementType === 'purchase' ||
    mvt.movementType === 'waste' ||
    mvt.movementType === 'production';

  return { direction, isSale, isAdmin };
}
