-- 20260618000012_revoke_anon_get_orders_list_v2.sql
-- S25 canonical pattern.

REVOKE EXECUTE ON FUNCTION public.get_orders_list_v2(TEXT, TEXT, JSONB, INT, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_orders_list_v2(TEXT, TEXT, JSONB, INT, TIMESTAMPTZ) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
