-- Session 27c / Wave 2 — Canonical REVOKE pair (S20 pattern).

REVOKE EXECUTE ON FUNCTION reorder_variants_v1(UUID, UUID[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION reorder_variants_v1(UUID, UUID[]) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
