REVOKE EXECUTE ON FUNCTION set_expense_threshold_v1(UUID, UUID, NUMERIC, NUMERIC, JSONB) FROM anon;
REVOKE EXECUTE ON FUNCTION set_expense_threshold_v1(UUID, UUID, NUMERIC, NUMERIC, JSONB) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
