-- 20260618000020_revoke_anon_remove_order_item_v1.sql
REVOKE EXECUTE ON FUNCTION public.remove_order_item_v1(UUID, UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.remove_order_item_v1(UUID, UUID) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
