-- 20260517000091_create_opname_rpcs.sql
-- Session 13 / Phase 2.D — Opname workflow RPCs.
--
-- Six high-level RPCs (SECURITY DEFINER, gated by has_permission) :
--   1. create_opname_v1   (MANAGER+ inventory.opname.create)
--   2. add_opname_item_v1 (MANAGER+ inventory.opname.create)
--   3. set_opname_count_v1 (MANAGER+ inventory.opname.create)
--   4. validate_opname_v1 (MANAGER+ inventory.opname.create) — draft|counting → review
--   5. finalize_opname_v1 (ADMIN+ inventory.opname.finalize)   — review|counting → finalized
--   6. cancel_opname_v1   (MANAGER+ inventory.opname.create)
--
-- finalize_opname_v1 emits ONE stock_movement per non-zero-variance row via
-- record_stock_movement_v1 (000020 v5). The companion trigger tr_20_je_emit
-- (000023) posts the JE :
--   variance > 0  → movement_type='opname_in'  → DR INVENTORY_GENERAL / CR OPNAME_INCOME
--   variance < 0  → movement_type='opname_out' → DR OPNAME_EXPENSE    / CR INVENTORY_GENERAL
--
-- IMPORTANT (Phase 2.D Deviation D-W2-2D-01) : the spec mentioned
-- 'opname_adjust_up' / 'opname_adjust_down' but tr_20_je_emit (Phase 1.A
-- migration 000022) handles 'opname_in' / 'opname_out' which were seeded in
-- the enum by migration 000014. We use the existing enum values to keep the
-- JE path live with no further enum extension.

-- =============================================================
-- 1. create_opname_v1
-- =============================================================

CREATE OR REPLACE FUNCTION create_opname_v1(
  p_section_id      UUID,
  p_notes           TEXT  DEFAULT NULL,
  p_idempotency_key UUID  DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid          UUID := auth.uid();
  v_profile      UUID;
  v_count_id     UUID;
  v_count_number TEXT;
  v_section_active BOOLEAN;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.create') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  IF p_idempotency_key IS NOT NULL THEN
    SELECT id, count_number INTO v_count_id, v_count_number
      FROM inventory_counts WHERE idempotency_key = p_idempotency_key;
    IF FOUND THEN
      RETURN jsonb_build_object(
        'count_id',          v_count_id,
        'count_number',      v_count_number,
        'idempotent_replay', true
      );
    END IF;
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  IF p_section_id IS NULL THEN
    RAISE EXCEPTION 'section_required';
  END IF;

  SELECT is_active INTO v_section_active
    FROM sections WHERE id = p_section_id AND deleted_at IS NULL;
  IF NOT FOUND OR v_section_active = false THEN
    RAISE EXCEPTION 'section_not_found' USING ERRCODE='P0002';
  END IF;

  v_count_number := next_count_number();

  INSERT INTO inventory_counts (
    count_number, section_id, status, created_by, notes, idempotency_key
  ) VALUES (
    v_count_number, p_section_id, 'draft', v_profile, p_notes, p_idempotency_key
  ) RETURNING id INTO v_count_id;

  INSERT INTO audit_log (action, subject_table, subject_id, payload, actor_profile_id)
  VALUES (
    'opname.create', 'inventory_counts', v_count_id,
    jsonb_build_object(
      'count_number',  v_count_number,
      'section_id',    p_section_id,
      'idempotency_key', p_idempotency_key
    ),
    v_profile
  );

  RETURN jsonb_build_object(
    'count_id',          v_count_id,
    'count_number',      v_count_number,
    'status',            'draft',
    'idempotent_replay', false
  );
END $$;

REVOKE EXECUTE ON FUNCTION create_opname_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION create_opname_v1 TO authenticated;

COMMENT ON FUNCTION create_opname_v1 IS
  'Session 13 — Phase 2.D. MANAGER+ (inventory.opname.create). Opens a draft '
  'opname for a section. count_number autogenerated. Idempotent via p_idempotency_key.';

-- =============================================================
-- 2. add_opname_item_v1 — auto-loads expected_qty from section_stock
-- =============================================================

CREATE OR REPLACE FUNCTION add_opname_item_v1(
  p_count_id     UUID,
  p_product_id   UUID,
  p_expected_qty DECIMAL(10,3) DEFAULT NULL,
  p_notes        TEXT          DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid          UUID := auth.uid();
  v_profile      UUID;
  v_status       TEXT;
  v_section_id   UUID;
  v_product_unit TEXT;
  v_expected     DECIMAL(10,3);
  v_item_id      UUID;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.create') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT status, section_id INTO v_status, v_section_id
    FROM inventory_counts WHERE id = p_count_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'count_not_found' USING ERRCODE='P0002';
  END IF;

  IF v_status NOT IN ('draft','counting') THEN
    RAISE EXCEPTION 'add_item_not_allowed_in_status';
  END IF;

  SELECT unit INTO v_product_unit FROM products
    WHERE id = p_product_id AND deleted_at IS NULL;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'product_not_found' USING ERRCODE='P0002';
  END IF;

  IF p_expected_qty IS NULL THEN
    SELECT COALESCE(quantity, 0) INTO v_expected
      FROM section_stock
      WHERE section_id = v_section_id AND product_id = p_product_id;
    IF v_expected IS NULL THEN
      v_expected := 0;
    END IF;
  ELSE
    v_expected := p_expected_qty;
  END IF;

  INSERT INTO inventory_count_items (
    count_id, product_id, expected_qty, unit, notes
  ) VALUES (
    p_count_id, p_product_id, v_expected, COALESCE(v_product_unit, 'pcs'), p_notes
  )
  ON CONFLICT (count_id, product_id) DO UPDATE
    SET expected_qty = EXCLUDED.expected_qty,
        unit         = EXCLUDED.unit,
        notes        = EXCLUDED.notes,
        updated_at   = now()
  RETURNING id INTO v_item_id;

  -- Flip status from draft to counting on first item.
  IF v_status = 'draft' THEN
    UPDATE inventory_counts SET status = 'counting' WHERE id = p_count_id;
  END IF;

  RETURN jsonb_build_object(
    'item_id',      v_item_id,
    'count_id',     p_count_id,
    'product_id',   p_product_id,
    'expected_qty', v_expected,
    'unit',         COALESCE(v_product_unit, 'pcs')
  );
END $$;

REVOKE EXECUTE ON FUNCTION add_opname_item_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION add_opname_item_v1 TO authenticated;

COMMENT ON FUNCTION add_opname_item_v1 IS
  'Session 13 — Phase 2.D. MANAGER+ (inventory.opname.create). Adds (or upserts) '
  'a product row on an opname. When p_expected_qty is NULL, auto-loads from '
  'section_stock.quantity. First item flips count.status draft -> counting.';

-- =============================================================
-- 3. set_opname_count_v1
-- =============================================================

CREATE OR REPLACE FUNCTION set_opname_count_v1(
  p_count_item_id UUID,
  p_counted_qty   DECIMAL(10,3),
  p_notes         TEXT DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid     UUID := auth.uid();
  v_profile UUID;
  v_count_id UUID;
  v_status  TEXT;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.create') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  IF p_counted_qty IS NULL OR p_counted_qty < 0 THEN
    RAISE EXCEPTION 'counted_qty_invalid';
  END IF;

  SELECT count_id INTO v_count_id
    FROM inventory_count_items WHERE id = p_count_item_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'count_item_not_found' USING ERRCODE='P0002';
  END IF;

  SELECT status INTO v_status
    FROM inventory_counts WHERE id = v_count_id FOR UPDATE;

  IF v_status NOT IN ('draft','counting','review') THEN
    RAISE EXCEPTION 'set_count_not_allowed_in_status';
  END IF;

  UPDATE inventory_count_items
    SET counted_qty = p_counted_qty,
        notes       = COALESCE(p_notes, notes),
        updated_at  = now()
    WHERE id = p_count_item_id;

  RETURN jsonb_build_object(
    'item_id',     p_count_item_id,
    'count_id',    v_count_id,
    'counted_qty', p_counted_qty
  );
END $$;

REVOKE EXECUTE ON FUNCTION set_opname_count_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION set_opname_count_v1 TO authenticated;

COMMENT ON FUNCTION set_opname_count_v1 IS
  'Session 13 — Phase 2.D. MANAGER+ (inventory.opname.create). Records counted_qty '
  'on an item. variance column is GENERATED so no app compute needed. Allowed '
  'while status is draft / counting / review.';

-- =============================================================
-- 4. validate_opname_v1 — counting|draft → review
-- =============================================================

CREATE OR REPLACE FUNCTION validate_opname_v1(
  p_count_id UUID
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid     UUID := auth.uid();
  v_profile UUID;
  v_status  TEXT;
  v_missing INT;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.create') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT status INTO v_status FROM inventory_counts
    WHERE id = p_count_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'count_not_found' USING ERRCODE='P0002';
  END IF;

  IF v_status NOT IN ('draft','counting') THEN
    RAISE EXCEPTION 'validate_not_allowed_in_status';
  END IF;

  SELECT COUNT(*) INTO v_missing FROM inventory_count_items
    WHERE count_id = p_count_id AND counted_qty IS NULL;
  IF v_missing > 0 THEN
    RAISE EXCEPTION 'missing_counts' USING DETAIL=format('%s row(s) missing counted_qty', v_missing);
  END IF;

  UPDATE inventory_counts
    SET status = 'review'
    WHERE id = p_count_id;

  RETURN jsonb_build_object(
    'count_id', p_count_id,
    'status',   'review'
  );
END $$;

REVOKE EXECUTE ON FUNCTION validate_opname_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION validate_opname_v1 TO authenticated;

COMMENT ON FUNCTION validate_opname_v1 IS
  'Session 13 — Phase 2.D. MANAGER+ (inventory.opname.create). Transitions a '
  'draft|counting opname to review after asserting every item row has a counted_qty.';

-- =============================================================
-- 5. finalize_opname_v1 — emits adjustments + JE via trigger
-- =============================================================

CREATE OR REPLACE FUNCTION finalize_opname_v1(
  p_count_id        UUID,
  p_idempotency_key UUID DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid           UUID := auth.uid();
  v_profile       UUID;
  v_status        TEXT;
  v_section_id    UUID;
  v_count_number  TEXT;
  v_item          RECORD;
  v_movement      JSONB;
  v_movement_id   UUID;
  v_mvt_type      TEXT;
  v_qty           DECIMAL(10,3);
  v_movements     JSONB := '[]'::JSONB;
  v_emitted       INT := 0;
  v_existing_status TEXT;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.finalize') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT status, section_id, count_number
    INTO v_status, v_section_id, v_count_number
    FROM inventory_counts WHERE id = p_count_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'count_not_found' USING ERRCODE='P0002';
  END IF;

  -- Idempotent replay : if already finalized and key matches, return cached movements.
  IF v_status = 'finalized' THEN
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
            'movement_id', sm.id,
            'product_id',  sm.product_id,
            'movement_type', sm.movement_type,
            'quantity',    sm.quantity,
            'unit',        sm.unit
          ) ORDER BY sm.created_at), '[]'::JSONB)
      INTO v_movements
      FROM stock_movements sm
      WHERE sm.reference_type = 'opname' AND sm.reference_id = p_count_id;
    RETURN jsonb_build_object(
      'count_id',          p_count_id,
      'count_number',      v_count_number,
      'status',            'finalized',
      'idempotent_replay', true,
      'movements_emitted', jsonb_array_length(v_movements),
      'movements',         v_movements
    );
  END IF;

  IF v_status NOT IN ('counting','review') THEN
    RAISE EXCEPTION 'finalize_not_allowed_in_status';
  END IF;

  -- Pre-check : no NULL counted_qty (in case finalize is called without validate).
  IF EXISTS (SELECT 1 FROM inventory_count_items
              WHERE count_id = p_count_id AND counted_qty IS NULL) THEN
    RAISE EXCEPTION 'missing_counts';
  END IF;

  -- Emit one movement per non-zero variance row.
  FOR v_item IN
    SELECT ici.id, ici.product_id, ici.variance, ici.unit, ici.expected_qty, ici.counted_qty
      FROM inventory_count_items ici
      WHERE ici.count_id = p_count_id AND COALESCE(ici.variance, 0) <> 0
  LOOP
    v_qty := ABS(v_item.variance);
    IF v_item.variance > 0 THEN
      v_mvt_type := 'opname_in';
      -- positive variance : section_stock GREW vs expected -> push +qty into section
      v_movement := record_stock_movement_v1(
        p_product_id      := v_item.product_id,
        p_movement_type   := 'opname_in'::movement_type,
        p_quantity        := v_qty,
        p_reason          := 'Opname ' || v_count_number || ' variance + ' || v_qty,
        p_unit_cost       := NULL,
        p_supplier_id     := NULL,
        p_idempotency_key := NULL,
        p_unit            := v_item.unit,
        p_from_section_id := NULL,
        p_to_section_id   := v_section_id,
        p_metadata        := jsonb_build_object(
                               'count_id',      p_count_id,
                               'count_number',  v_count_number,
                               'count_item_id', v_item.id,
                               'expected_qty',  v_item.expected_qty,
                               'counted_qty',   v_item.counted_qty
                             ),
        p_lot_id          := NULL
      );
    ELSE
      v_mvt_type := 'opname_out';
      v_movement := record_stock_movement_v1(
        p_product_id      := v_item.product_id,
        p_movement_type   := 'opname_out'::movement_type,
        p_quantity        := -v_qty,
        p_reason          := 'Opname ' || v_count_number || ' variance - ' || v_qty,
        p_unit_cost       := NULL,
        p_supplier_id     := NULL,
        p_idempotency_key := NULL,
        p_unit            := v_item.unit,
        p_from_section_id := v_section_id,
        p_to_section_id   := NULL,
        p_metadata        := jsonb_build_object(
                               'count_id',      p_count_id,
                               'count_number',  v_count_number,
                               'count_item_id', v_item.id,
                               'expected_qty',  v_item.expected_qty,
                               'counted_qty',   v_item.counted_qty
                             ),
        p_lot_id          := NULL
      );
    END IF;

    v_movement_id := (v_movement->>'movement_id')::UUID;
    UPDATE stock_movements
      SET reference_type = 'opname', reference_id = p_count_id
      WHERE id = v_movement_id;

    UPDATE inventory_count_items
      SET movement_id = v_movement_id, updated_at = now()
      WHERE id = v_item.id;

    v_movements := v_movements || jsonb_build_array(jsonb_build_object(
      'movement_id',   v_movement_id,
      'product_id',    v_item.product_id,
      'movement_type', v_mvt_type,
      'variance',      v_item.variance,
      'quantity',      v_qty,
      'unit',          v_item.unit
    ));
    v_emitted := v_emitted + 1;
  END LOOP;

  UPDATE inventory_counts
    SET status           = 'finalized',
        finalized_by     = v_profile,
        finalized_at     = now(),
        idempotency_key  = COALESCE(idempotency_key, p_idempotency_key),
        metadata         = metadata || jsonb_build_object(
                                         'movements_emitted', v_emitted,
                                         'finalized_at',      now()
                                       )
    WHERE id = p_count_id;

  INSERT INTO audit_log (action, subject_table, subject_id, payload, actor_profile_id)
  VALUES (
    'opname.finalize', 'inventory_counts', p_count_id,
    jsonb_build_object(
      'count_number',      v_count_number,
      'section_id',        v_section_id,
      'movements_emitted', v_emitted,
      'idempotency_key',   p_idempotency_key
    ),
    v_profile
  );

  RETURN jsonb_build_object(
    'count_id',          p_count_id,
    'count_number',      v_count_number,
    'status',            'finalized',
    'idempotent_replay', false,
    'movements_emitted', v_emitted,
    'movements',         v_movements
  );
END $$;

REVOKE EXECUTE ON FUNCTION finalize_opname_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION finalize_opname_v1 TO authenticated;

COMMENT ON FUNCTION finalize_opname_v1 IS
  'Session 13 — Phase 2.D. ADMIN+ (inventory.opname.finalize). Transitions '
  'counting|review opname to finalized. Emits one stock_movement per non-zero '
  'variance row (opname_in for variance>0, opname_out for variance<0). The JE '
  'is posted by tr_20_je_emit (000023) via OPNAME_INCOME / OPNAME_EXPENSE / '
  'INVENTORY_GENERAL mappings. Idempotent : replay on a finalized count returns '
  'cached movements.';

-- =============================================================
-- 6. cancel_opname_v1 — non-finalized → cancelled
-- =============================================================

CREATE OR REPLACE FUNCTION cancel_opname_v1(
  p_count_id UUID,
  p_reason   TEXT
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid          UUID := auth.uid();
  v_profile      UUID;
  v_status       TEXT;
  v_count_number TEXT;
BEGIN
  IF NOT has_permission(v_uid, 'inventory.opname.create') THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  IF p_reason IS NULL OR length(trim(p_reason)) < 3 THEN
    RAISE EXCEPTION 'reason_required';
  END IF;

  SELECT id INTO v_profile FROM user_profiles
    WHERE auth_user_id = v_uid AND deleted_at IS NULL;
  IF v_profile IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE='P0003';
  END IF;

  SELECT status, count_number INTO v_status, v_count_number
    FROM inventory_counts WHERE id = p_count_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'count_not_found' USING ERRCODE='P0002';
  END IF;

  IF v_status = 'finalized' THEN
    RAISE EXCEPTION 'cancel_not_allowed_after_finalize';
  END IF;
  IF v_status = 'cancelled' THEN
    RAISE EXCEPTION 'already_cancelled';
  END IF;

  UPDATE inventory_counts
    SET status        = 'cancelled',
        cancelled_by  = v_profile,
        cancelled_at  = now(),
        cancel_reason = p_reason,
        metadata      = metadata || jsonb_build_object(
                                      'previous_status', v_status,
                                      'cancelled_at',    now()
                                    )
    WHERE id = p_count_id;

  INSERT INTO audit_log (action, subject_table, subject_id, payload, actor_profile_id)
  VALUES (
    'opname.cancel', 'inventory_counts', p_count_id,
    jsonb_build_object(
      'count_number',    v_count_number,
      'cancel_reason',   p_reason,
      'previous_status', v_status
    ),
    v_profile
  );

  RETURN jsonb_build_object(
    'count_id',      p_count_id,
    'status',        'cancelled',
    'cancel_reason', p_reason
  );
END $$;

REVOKE EXECUTE ON FUNCTION cancel_opname_v1 FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION cancel_opname_v1 TO authenticated;

COMMENT ON FUNCTION cancel_opname_v1 IS
  'Session 13 — Phase 2.D. MANAGER+ (inventory.opname.create). Cancels a '
  'non-finalized opname with a reason (>=3 chars). Refused once status=finalized '
  'or already cancelled.';
