-- 20260618000016_revoke_anon_add_order_item_v1.sql
REVOKE EXECUTE ON FUNCTION public.add_order_item_v1(UUID, UUID, INT, JSONB, UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.add_order_item_v1(UUID, UUID, INT, JSONB, UUID) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
