REVOKE EXECUTE ON FUNCTION delete_expense_threshold_v1(UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION delete_expense_threshold_v1(UUID) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
