-- Session 27c / Wave 2 — Canonical REVOKE pair (S20 pattern).

REVOKE EXECUTE ON FUNCTION update_variant_v1(UUID, JSONB) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION update_variant_v1(UUID, JSONB) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
