-- Canonical S25 REVOKE pair for delete_category_v1.
GRANT EXECUTE ON FUNCTION public.delete_category_v1(UUID, UUID) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.delete_category_v1(UUID, UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_category_v1(UUID, UUID) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon;
