REVOKE EXECUTE ON FUNCTION reorder_categories_v1(UUID[]) FROM anon;
REVOKE EXECUTE ON FUNCTION reorder_categories_v1(UUID[]) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
GRANT EXECUTE ON FUNCTION reorder_categories_v1(UUID[]) TO authenticated;
