-- Session 27c / Wave 2 — Canonical REVOKE pair (S20 pattern).

REVOKE EXECUTE ON FUNCTION create_variant_v1(UUID, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, INTEGER, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_variant_v1(UUID, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, INTEGER, TEXT) FROM anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
