-- 20260517000090_init_inventory_counts.sql
-- Session 13 / Phase 2.D — Inventory opname (Session 12 phase 5).
--
-- Creates the opname (stock-count) header + items tables. Workflow :
--   1. create_opname_v1   : opens a draft count for a section.
--   2. add_opname_item_v1 : adds a product row, auto-loading expected_qty
--                            from section_stock when caller passes NULL.
--   3. set_opname_count_v1: records the counted_qty (variance is GENERATED).
--   4. validate_opname_v1 : draft → review (no movement emitted yet).
--   5. finalize_opname_v1 : review|draft → finalized — emits ONE
--                            stock_movement per row with variance != 0
--                            (opname_in for +ve, opname_out for -ve).
--                            tr_20_je_emit (000023) posts the JE.
--   6. cancel_opname_v1   : any non-finalized status → cancelled.
--
-- count_number format : OPN-YYYYMMDD-NNNN (sequence, padded to 4 digits).
--
-- Phantom audit (W1-C4 grep gate) : NEVER re-CREATE has_permission(). New
-- perm rows are added below into permissions + role_permissions (already
-- present from migration 000018 → idempotent ON CONFLICT). The has_perm
-- v8 refactor (000030) is data-driven : new rows are picked up automatically.

-- =============================================================
-- inventory_counts — opname header
-- =============================================================

CREATE TABLE inventory_counts (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  count_number    TEXT         NOT NULL UNIQUE,
  section_id      UUID         NOT NULL REFERENCES sections(id) ON DELETE RESTRICT,
  status          TEXT         NOT NULL DEFAULT 'draft'
                                CHECK (status IN ('draft','counting','review','finalized','cancelled')),
  created_by      UUID         NOT NULL REFERENCES user_profiles(id) ON DELETE RESTRICT,
  finalized_by    UUID         REFERENCES user_profiles(id) ON DELETE SET NULL,
  cancelled_by    UUID         REFERENCES user_profiles(id) ON DELETE SET NULL,
  started_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  finalized_at    TIMESTAMPTZ,
  cancelled_at    TIMESTAMPTZ,
  cancel_reason   TEXT,
  notes           TEXT,
  metadata        JSONB        NOT NULL DEFAULT '{}'::JSONB,
  idempotency_key UUID         UNIQUE,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_inventory_counts_section_status
  ON inventory_counts(section_id, status, created_at DESC);

CREATE INDEX idx_inventory_counts_status_started
  ON inventory_counts(status, started_at DESC);

CREATE TRIGGER inventory_counts_set_updated_at
  BEFORE UPDATE ON inventory_counts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE inventory_counts IS
  'Session 13 — Phase 2.D. Opname (stock-count) header. Workflow : '
  'draft → counting → review → finalized OR draft|counting|review → cancelled. '
  'On finalize, one stock_movement is emitted per non-zero variance row, '
  'tr_20_je_emit (000023) posts the JE via OPNAME_INCOME / OPNAME_EXPENSE / INVENTORY_GENERAL.';

COMMENT ON COLUMN inventory_counts.count_number IS
  'Format OPN-YYYYMMDD-NNNN, generated by next_count_number() in migration 000091.';
COMMENT ON COLUMN inventory_counts.status IS
  'draft (open), counting (UI flag), review (pending validation), finalized (immutable), cancelled.';

-- =============================================================
-- inventory_count_items — opname rows (one per product per count)
-- =============================================================

CREATE TABLE inventory_count_items (
  id            UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  count_id      UUID           NOT NULL REFERENCES inventory_counts(id) ON DELETE CASCADE,
  product_id    UUID           NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  expected_qty  DECIMAL(10,3)  NOT NULL DEFAULT 0,
  counted_qty   DECIMAL(10,3),
  variance      DECIMAL(10,3)  GENERATED ALWAYS AS (counted_qty - expected_qty) STORED,
  unit          TEXT           NOT NULL,
  movement_id   UUID,
  notes         TEXT,
  created_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ    NOT NULL DEFAULT now(),
  UNIQUE (count_id, product_id)
);

CREATE INDEX idx_inventory_count_items_count
  ON inventory_count_items(count_id);
CREATE INDEX idx_inventory_count_items_product
  ON inventory_count_items(product_id);

CREATE TRIGGER inventory_count_items_set_updated_at
  BEFORE UPDATE ON inventory_count_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE inventory_count_items IS
  'Session 13 — Phase 2.D. One row per product counted in an opname. '
  'variance is GENERATED ALWAYS AS (counted_qty - expected_qty) STORED so '
  'every read sees a consistent value with no app-side compute.';

COMMENT ON COLUMN inventory_count_items.expected_qty IS
  'Snapshot of the section_stock.quantity at the moment the item was added. '
  'Held constant for the count to give a stable reference even if section_stock '
  'changes mid-count.';
COMMENT ON COLUMN inventory_count_items.counted_qty IS
  'NULL until set_opname_count_v1 records a value. NOT NULL becomes a precondition '
  'for the finalize_opname_v1 RPC (raises missing_counts).';
COMMENT ON COLUMN inventory_count_items.movement_id IS
  'Set by finalize_opname_v1 to the emitted stock_movement row (opname_in / opname_out). '
  'NULL for rows with variance = 0 (no movement emitted).';

-- =============================================================
-- count_number sequence + helper
-- =============================================================

CREATE SEQUENCE inventory_counts_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 1;

CREATE OR REPLACE FUNCTION next_count_number()
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_day TEXT := to_char(now() AT TIME ZONE 'UTC', 'YYYYMMDD');
  v_seq BIGINT;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('next_count_number-' || v_day));
  v_seq := nextval('inventory_counts_seq');
  RETURN 'OPN-' || v_day || '-' || lpad(v_seq::TEXT, 4, '0');
END $$;

REVOKE EXECUTE ON FUNCTION next_count_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION next_count_number() FROM authenticated;

COMMENT ON FUNCTION next_count_number() IS
  'INTERNAL — produces OPN-YYYYMMDD-NNNN. Locked via pg_advisory_xact_lock '
  'on the day to keep numbers monotonic per day.';

-- =============================================================
-- RLS — auth_read + write via SECURITY DEFINER RPCs only
-- =============================================================

ALTER TABLE inventory_counts       ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_count_items  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth_read" ON inventory_counts FOR SELECT
  USING (is_authenticated());

CREATE POLICY "auth_read" ON inventory_count_items FOR SELECT
  USING (is_authenticated());

-- No INSERT/UPDATE/DELETE policies — only SECURITY DEFINER RPCs write.
-- Revoke explicit DML grants for authenticated to harden against accidental
-- direct calls (RLS would block anyway, but belt-and-braces).
REVOKE INSERT, UPDATE, DELETE ON inventory_counts      FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON inventory_count_items FROM authenticated;

-- =============================================================
-- Permissions — already seeded in 000018, but we INSERT defensively
-- with ON CONFLICT to be idempotent.
-- =============================================================

INSERT INTO permissions (code, module, action, description) VALUES
  ('inventory.opname.create',   'inventory', 'create',
   'Create / participate in stock opname session — MANAGER+'),
  ('inventory.opname.finalize', 'inventory', 'update',
   'Finalize opname (emits adjustment movements + JE) — ADMIN+')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (role_code, permission_code) VALUES
  ('MANAGER',     'inventory.opname.create'),
  ('ADMIN',       'inventory.opname.create'),
  ('ADMIN',       'inventory.opname.finalize'),
  ('SUPER_ADMIN', 'inventory.opname.create'),
  ('SUPER_ADMIN', 'inventory.opname.finalize')
ON CONFLICT DO NOTHING;
