REVOKE EXECUTE ON FUNCTION approve_expense_v2(UUID) FROM anon;
REVOKE EXECUTE ON FUNCTION approve_expense_v2(UUID) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
