REVOKE EXECUTE ON FUNCTION update_category_v1(UUID, JSONB) FROM anon;
REVOKE EXECUTE ON FUNCTION update_category_v1(UUID, JSONB) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
GRANT EXECUTE ON FUNCTION update_category_v1(UUID, JSONB) TO authenticated;
