REVOKE EXECUTE ON FUNCTION create_category_v1(JSONB) FROM anon;
REVOKE EXECUTE ON FUNCTION create_category_v1(JSONB) FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_category_v1(JSONB) TO authenticated;
